name: amu
description: "Weaving code into stories."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  audioplayers: ^6.0.0
  google_fonts: ^6.1.0
  google_generative_ai: ^0.4.0
  file_picker: ^8.0.0
  http: ^1.6.0

flutter:
  uses-material-design: true
  assets:

    - assets/audio/
    - assets/photo/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/photo/icon.png"
  web:
    generate: true
    image_path: "assets/photo/icon.png"
    background_color: "#0F172A"
    theme_color: "#0F172A"
  macos:
    generate: true
    image_path: "assets/photo/icon.png"
